In [52]:
import torch

In [53]:
# Create a tensor and set requires_grad=True to track computation with it
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [54]:
# Do an operation of tensor
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [55]:
# y was created as a result of an operation, so it has a grad_fn
print(y.grad_fn)

In [56]:
# more operations on y
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [57]:
# .requires_grad_( ... ) changes an existing Tensor's requires_grad flag in-place. The input flag defaults to True if not given.
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Gradients
---------
Let's backprop now
Because ``out`` contains a single scalar, ``out.backward()`` is
equivalent to ``out.backward(torch.tensor(1))``.

In [58]:
out.backward()

In [59]:
# print gradients d(out)/dx
print(x.grad)

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.



In [60]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
i = 1
while y.data.norm() < 1000:
    i += 1
    y = y * 2

print(y)
print(i)
print(2 ** i)

tensor([-0.8112,  0.6687,  1.1073])
tensor([ -830.6543,   684.7815,  1133.8246])
10
1024


In [61]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients) # gradients with respect to each element of given tensor <gradients>

print(x.grad)

tensor([  102.4000,  1024.0000,     0.1024])


In [51]:
# stop autograd from tracking history on Tensors with requires_grad=True
# by wrapping the code block in with torch.no_grad():
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)

True
True
False
