In [25]:
from __future__ import print_function
import torch
import numpy as np

In [7]:
# ======
# Basics
# ======
# Similar to NumPy’s ndarrays, with the addition being that
# Tensors can also be used on a GPU to accelerate computing

In [8]:
# construct a 5x3 unintialized matrix
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-10 *
       [[ 0.0000, -0.0000,  0.0000],
        [-4.6577, -0.0000,  0.0000],
        [-0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [9]:
# construct a 5x3 randomly initialzed matrix 
x = torch.rand(5, 3)
print(x)

tensor([[ 0.9797,  0.7443,  0.6481],
        [ 0.4594,  0.1940,  0.9718],
        [ 0.4622,  0.3353,  0.3297],
        [ 0.2188,  0.2420,  0.2348],
        [ 0.3357,  0.6331,  0.3104]])


In [10]:
# construct a matrix filled zeros and of dtype long 
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [11]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([ 5.5000,  3.0000])


In [12]:
# Create a tensor basing on existing tensor
# These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[-1.2948, -0.4454, -1.0649],
        [-1.4798,  1.6568, -0.6378],
        [-0.5081,  0.9260,  0.7113],
        [-0.7113,  2.0429,  0.5110],
        [-0.3011,  0.6388,  0.6254]])


In [14]:
print(x.size()) # Get its size. The result is in fact a tuple

torch.Size([5, 3])


In [15]:
# ==========
# Operations
# ==========

In [18]:
# Addtion - multiple syntaxes
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# in-place addition
# adds x to y
y.add_(x)
print(y)

tensor([[-0.8056,  0.4835, -0.4489],
        [-0.6633,  1.9559, -0.2685],
        [-0.1561,  1.0765,  1.5686],
        [-0.6337,  2.9110,  1.2364],
        [ 0.5746,  1.2079,  1.1262]])
tensor([[-0.8056,  0.4835, -0.4489],
        [-0.6633,  1.9559, -0.2685],
        [-0.1561,  1.0765,  1.5686],
        [-0.6337,  2.9110,  1.2364],
        [ 0.5746,  1.2079,  1.1262]])
tensor([[-0.8056,  0.4835, -0.4489],
        [-0.6633,  1.9559, -0.2685],
        [-0.1561,  1.0765,  1.5686],
        [-0.6337,  2.9110,  1.2364],
        [ 0.5746,  1.2079,  1.1262]])
tensor([[-0.8056,  0.4835, -0.4489],
        [-0.6633,  1.9559, -0.2685],
        [-0.1561,  1.0765,  1.5686],
        [-0.6337,  2.9110,  1.2364],
        [ 0.5746,  1.2079,  1.1262]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>




In [19]:
# numpy-like indexing
print(x[:, 1])

tensor([-0.4454,  1.6568,  0.9260,  2.0429,  0.6388])


In [20]:
# reshape tensor: torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.6080])
0.6079737544059753


In [22]:
# ============
# NumPy Bridge
# ============
# The Torch Tensor and NumPy array will share their underlying memory locations
# changing one will change the other.

In [23]:
# Torch Tensor => NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[1. 1. 1. 1. 1.]


In [24]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [28]:
# Numpy Array => Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
